[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
fs_permissions = [{ access = "read", path = "./contracts/out"}, { access = "write", path = "genesis.json"}]
cancun = true
ffi = true
solc_version = "0.8.26"
